### PR TITLE
Make compatible with Python 3.10

### PR DESCRIPTION
**Pull request by carderne**
As discussed in #26

### CODE REVIEW

**Comment by carderne** [comment]
@rigglemania it would great if you could merge this, as currently https://github.com/carderne/signal-export is broken on Python 3.10.

This doesn't introduce any breaking changes.

**Comment by rigglemania** [comment]
Does this change impact at all what minimum version of Python is supported?  For example, something like if this change was merged, this code wouldn't work with versions before Python 3.7?

**Comment by carderne** [comment]
Tested and working back to Python 3.6.

This API seems to have been [available since Python 3.3](https://docs.python.org/3.5/c-api/unicode.html#c.PyUnicode_AsUTF8AndSize).

**Comment by rigglemania** [comment]
So this would break anyone on Python 3.2. Granted, It looks like Python 3.3 came out in 2012, which is more than enough time to update. But at a minimum, make sure your PR includes a version bump so at least existing users won't be automatically broken but only if they choose to upgrade to the latest version.

**Comment by carderne** [comment]
Done and added `python_requires` constraint to setup.py.

**Comment by rigglemania** [comment]
Merged and I published the updated version. I think I uploaded the updated version correctly, but I've been out of the python world for a bit, so let me know if anything is wrong with the latest upload. Thanks for the contribution!

**Comment by carderne** [comment]
Tested the release and all working well.

**Pull request merged**
